webapp/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Blitzmove.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

webapp/Pages/Favorites.cshtml.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Blitzmove.Models;
using Microsoft.AspNetCore.Identity;


namespace Blitzmove.Pages
{
    public class FavoritesModel : PageModel
    {
        private readonly IAdsService adsService;

        private UserManager<ApplicationUser> _userManager;

        private UserFavorites FavList;
        public ApplicationUser appUser { get; private set; }

        public Place[] MyFavorites { get; set; } = new Place[0];

        public FavoritesModel(UserManager<ApplicationUser> userManager, IAdsService adsService)
        {
            _userManager = userManager;
            this.adsService = adsService;
        }

        public async Task OnGetAsync()
        {
            appUser = await _userManager.GetUserAsync(User);
            var userid = Guid.Parse(appUser.Id);
            FavList = await adsService.FindUserFavoritesAsync(userid);
            if(FavList == null) return;


            MyFavorites = new Place[FavList.PlaceIds.Count];
            for(int i = 0; i < FavList.PlaceIds.Count; i++)
            {
                var place = await adsService.FindAsync(FavList.PlaceIds[i].PlaceId);
                if (place != null) MyFavorites[i] = place;
                else
                {
                    // in case the place has been deleted by the owner, we remove it from the user favorites
                    FavList.PlaceIds.Remove(
                        FavList.PlaceIds.Where(a => a.PlaceId == FavList.PlaceIds[i].PlaceId).First());

                    await adsService.UpdateUserFavoritesAsync(FavList);
                }
            }
        }

        public async Task<IActionResult> OnPostDeleteAsync(Guid fav)
        {
            appUser = await _userManager.GetUserAsync(User);
            var userid = Guid.Parse(appUser.Id);
            FavList = await adsService.FindUserFavoritesAsync(userid);
            
            FavList.PlaceIds.Remove(FavList.PlaceIds.Where(a => a.PlaceId == fav).First());
            await adsService.UpdateUserFavoritesAsync(FavList);
            return RedirectToPage();
        }
    }
}

webapp/Pages/Messages.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blitzmove.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;

namespace Blitzmove.Pages
{
    public class MessagesModel : PageModel
    {
        public class Contact
        {
            public Guid Id { get; set; }
            public string ProfilePic { get; set;}
        }

        private readonly IMessageService _messagesService;

        private readonly UserManager<ApplicationUser> _userManager;

        public ApplicationUser AppUser { get; private set; }
        
        public Dictionary<Guid, Tuple<string, List<Message>>> Conversations { get; private set; }

        public List<Message> CurrentConversationMessages { get; set; }

        public List<Contact> Contacts { get; set; } = new List<Contact>();

        public Guid ActiveConversationContactGuid { get; set; }

        public Guid SuperContactId {get; private set;} =  Guid.Parse("00000000-0000-0000-0000-000000000777");
        
        public string ActiveConversationContactName { get; set; }

        public Guid AppUserId { get; set; }

        [BindProperty]
        public string WrittenMessageFieldContent { get; set; }

        public MessagesModel(UserManager<ApplicationUser> userManager, IMessageService messagesService)
        {
            _userManager = userManager;
            _messagesService = messagesService;
        }

        private async Task InitializeModel()
        {
            AppUser = await _userManager.GetUserAsync(User);
            if (AppUser == null) return;
            AppUserId = Guid.Parse(AppUser.Id);
                        
            Conversations = new Dictionary<Guid, Tuple<string, List<Message>>>();
            var allMessages = await _messagesService.GetAllUserMessages(AppUser.Id);

            var senders = allMessages.Select(m => m.SenderGuid);
            var recipients = allMessages.Select(m => m.RecipientGuid);
            var listOfContactIds = senders.Concat(recipients).Distinct().ToList();

            // FILLING CONTACT LIST
            // 1 - Adding blitzmove as supercontact
            Contact superContact = new Contact{Id = SuperContactId, ProfilePic = null};
            Contacts.Add(superContact);
            // 2 - Adding normal contacts
            foreach(var cid in listOfContactIds)
            {
                var contactUser =  await _userManager.FindByIdAsync(cid.ToString());
                if(contactUser == null) continue;
                Contact elem = new Contact{Id = cid, ProfilePic = contactUser.ProfilePicture};
                Contacts.Add(elem);
            }
            // 3 - Removing ourselves from contact list
            Contacts.RemoveAll(x => x.Id == AppUserId);


            // FILLING DICTIONARY
            foreach (var contact in Contacts)
            {
                var exchangedWithContactOther = allMessages.AsParallel().Where(m => m.RecipientGuid.Equals(contact.Id));
                var exchangedWithContact = allMessages.AsParallel().Where(m => m.RecipientGuid.Equals(contact.Id) || m.SenderGuid.Equals(contact.Id));
                
                Conversations.Add(contact.Id, new Tuple<string, List<Message>>(
                                                await GetUsername(contact.Id),
                                                exchangedWithContact.OrderBy(m => m.CreatedDateTime).ToList()));
            }

            // By default, the 1rst contact is selected. In this case, it's the blitzmove supercontact 
            if(ActiveConversationContactGuid == Guid.Empty)
            {
                ActiveConversationContactGuid = Conversations.FirstOrDefault().Key;
                ActiveConversationContactName = await _messagesService.GetUsername(ActiveConversationContactGuid.ToString());
            }

            // List of messages to load in the partial view 
            CurrentConversationMessages = Conversations.ContainsKey(ActiveConversationContactGuid) 
                ? Conversations[ActiveConversationContactGuid].Item2 : new List<Message>();
        }

        private async Task<string> GetUsername(Guid id)
        {
            if (id == SuperContactId) return "Blitzmove";

            var username = await _messagesService.GetUsername(id.ToString());
            return username;
        }

        
        public async Task OnGetAsync()
        {
            await InitializeModel();
        }


        public async Task<IActionResult> OnGetConvoPartialAsync(string selectedContactId)
        {
            ActiveConversationContactGuid = Guid.Parse(selectedContactId);
            ActiveConversationContactName = await _messagesService.GetUsername(ActiveConversationContactGuid.ToString());
            await InitializeModel();
            return Partial("_ConversationPartial", this);
        }
        
        public IActionResult OnGetMessagePartial(string message, bool isSending, string ownerId)
        {
            var messagePartial = new PartialViewResult
            {
                ViewName = "_MessagePartial",
                ViewData = new ViewDataDictionary
                    <Tuple<string, bool, string>>(ViewData, Tuple.Create(message, isSending, ownerId))
            };

            return messagePartial;
        }

        public async Task<IActionResult> OnPostArchiveConversationAsync(string selectedContact)
        {
            AppUser = await _userManager.GetUserAsync(User);
            AppUserId = Guid.Parse(AppUser.Id);
            Guid contactGuid = Guid.Parse(selectedContact);

            await _messagesService.ArchiveConversation(AppUserId, contactGuid);

            return RedirectToPage();
        }
    }
}

webapp/Pages/MyPlaces.cshtml.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;  
using Blitzmove.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Blitzmove.Pages
{
    public class MyPlacesModel : PageModel
    {
        public class Applicant
        {
            public Guid Id { get; set; }
            public Guid ApplicationId { get; set; }
            public int ApplicationStatus { get; set; }
            public DateTime Appliedon { get; set; }
            public int PromisedReward { get; set; }
            public int CreditScore { get; set; }
            public int Salary { get; set; }
            public string JobTitle { get; set;}
            public string Username { get; set;}
            public string ProfilePic { get; set;}
            public string Details { get; set;}
        }

        public class MyPlace
        {
            public Place place { get; set;}
            public List<Applicant> ListOfApplicants { get; set; } = new List<Applicant>();
        }

        private readonly IAdsService _adsService;
        private readonly IApplicationsService _appsService;
        private readonly IMessageService _messagesService;
        private UserManager<ApplicationUser> _userManager;

        public ApplicationUser AppUser { get; private set; }

        public MyPlace[] MyPlaces { get; set; }

        [BindProperty]
        public string ApplicantId { get; set; }

        [BindProperty]
        public string Message { get; set; }

        public MyPlacesModel(UserManager<ApplicationUser> userManager, 
                             IAdsService adsService, IApplicationsService appsService, IMessageService messagesService)
        {
            _userManager = userManager;
            _adsService = adsService;
            _appsService = appsService;
            _messagesService = messagesService;
        }

        public async Task OnGetAsync()
        {
            AppUser = await _userManager.GetUserAsync(User);
            var places =  await _adsService.FindByUserAsync(AppUser.Id);

            MyPlaces = new MyPlace[places.Length];

            if(places == null || MyPlaces == null) return;
            
            for(int i = 0; i < places.Length; i++)
            {
                var place = places[i];
                var placeApplications =  await _appsService.FindByPlaceAsync(place.Id);

                // filling MyPlaces
                MyPlaces[i] = new MyPlace();
                MyPlaces[i].place = place;
                if(placeApplications != null && place != null)
                {
                    for(int k = 0; k < placeApplications.Length; k++)
                    {
                        // filling Applicants
                        Applicant item = new Applicant();
                        
                        item.Id = Guid.Parse(placeApplications[k].Applicant.Id);
                        item.ApplicationId = placeApplications[k].Id;
                        item.ApplicationStatus = placeApplications[k].Status;
                        item.Appliedon = placeApplications[k].CreationTime;
                        item.PromisedReward = placeApplications[k].PromisedReward;
                        item.Username = placeApplications[k].Applicant.Name;
                        item.ProfilePic = placeApplications[k].Applicant.ProfilePicture;
                        item.Details = placeApplications[k].Details;
                        item.CreditScore = placeApplications[k].Applicant.CreditScore;
                        item.JobTitle = placeApplications[k].Applicant.JobTitle;
                        item.Salary = placeApplications[k].Applicant.Salary;

                        MyPlaces[i].ListOfApplicants.Add(item);
                    }
                }
            }
        }

        public async Task<IActionResult> OnPostDeleteAsync(Guid id)
        {
            await _adsService.DeleteAsync(id);
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostMessageAsync()
        {
            AppUser = await _userManager.GetUserAsync(User);
            await _messagesService.SaveMessage(AppUser.Id, ApplicantId, this.Message);
            return RedirectToPage();
        }


        public async Task<IActionResult> OnPostDeclineAsync(Guid id, Guid query)
        {
            var placeApps =  await _appsService.FindByPlaceAsync(id);
            var place = await _adsService.FindAsync(id);
            var app = Array.Find(placeApps, x => x.Id.Equals(query));

            app.Status = 0;

            await _appsService.UpdateAsync(app);
            await notifyApplicant(place.Address, Guid.Parse(place.UserId) , Guid.Parse(app.Applicant.Id), 0);

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostInviteAsync(Guid id, Guid query)
        {
            var placeApps =  await _appsService.FindByPlaceAsync(id);
            var place = await _adsService.FindAsync(id);
            var app = Array.Find(placeApps, x => x.Id.Equals(query));

            app.Status = 1;

            await _appsService.UpdateAsync(app);
            await notifyApplicant(place.Address, Guid.Parse(place.UserId) , Guid.Parse(app.Applicant.Id), 1);

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostRequestPaymentAsync(Guid id, Guid query)
        {
            var placeApps =  await _appsService.FindByPlaceAsync(id);
            var place = await _adsService.FindAsync(id);
            var app = Array.Find(placeApps, x => x.Id.Equals(query));

            app.Status = 2;
            
            await _appsService.UpdateAsync(app);
            await notifyApplicant(place.Address, Guid.Parse(place.UserId) , Guid.Parse(app.Applicant.Id), 2);

            // disabling applications of the other applicants => Actions can no longer be taken by the poster
            var otherApps = placeApps.Where(p => p.Id != app.Id).ToArray();
            foreach(var other in otherApps)
            {
                other.Status = -2;
            }
            await _appsService.UpdateRangeAsync(otherApps);


            return RedirectToPage();
        }
         
        public async Task<IActionResult> OnPostCancelPaymentRequestAsync(Guid id, Guid query)
        {
            var placeApps =  await _appsService.FindByPlaceAsync(id);
            var place = await _adsService.FindAsync(id);
            var app = Array.Find(placeApps, x => x.Id.Equals(query));

            app.Status = -1; // default: in-progress
            await notifyApplicant(place.Address, Guid.Parse(place.UserId) , Guid.Parse(app.Applicant.Id), -1);

            await _appsService.UpdateAsync(app);

            // re-enabling applications of the other applicants => Actions can be taken by the poster
            var otherApps = placeApps.Where(p => p.Id != app.Id).ToArray();
            foreach(var other in otherApps)
            {
                other.Status = -1;
            }
            await _appsService.UpdateRangeAsync(otherApps);


            return RedirectToPage();
        }

        private async Task notifyApplicant(string placeAddress, Guid posterId, Guid applicantId, int type)
        {
            var poster =  await _userManager.FindByIdAsync(posterId.ToString());
            var applicant =  await _userManager.FindByIdAsync(applicantId.ToString());

            string message = "";

            if(type == 0){
                message += "Hi " + applicant.Name + ", Thank you for applying to my place located in " + placeAddress + 
                           ". Unfortunately, I will have to decline it. Best Regards, " + poster.Name;
            }
            else if(type == 1){
                message += "Hi " + applicant.Name + ", I would like to invite you to visit the place located in " + placeAddress + 
                           ". Let's schedule this ! Best Regards, " + poster.Name;
            }
            else if(type == 2){
                message += "Hi " + applicant.Name + 
                           ", Regarding your application to " + placeAddress + 
                           ", I am requesting the payment for the reward you promised in case of an agreement with the landlord. Best Regards, " + 
                           poster.Name;
            }
            else if(type == -1){
                message += "Sorry " + applicant.Name + ", I am cancelling the payment request I've made you previously. Best Regards, " + poster.Name;
            }
            else return;

            await _messagesService.SaveMessageAndEmail(posterId.ToString(), applicantId.ToString(), message, message);
        }
    }
}

webapp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Blitzmove.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

webapp/Pages/Faq.cshtml
@page
@{
    ViewData["Title"] = "FAQ";
}

<div style="text-align: justify" class="container col-md-8 pt-5">

    <h2 style="white-space: pre">Frequently Asked Questions</h2>

    <!-- <div class=bottompad>
        <div class="row">
            <div class=col-md-3>
                <p class="fs-20b"> Question </p>
            </div>
            <div class=col-md-9>
                <p class="fs-20b"> What would happen if a bad tenant came in, would it be the fault of the former tenant ?</p>
            </div>
        </div>

        <div class=row>
            <div class=col-md-3>
                <p class="fs-18"> Answer </p>
            </div>
            <div class=col-md-9>
                <p class="fs-18"> No. </p>
            </div>
        </div>
    </div> -->

</div>

@section Scripts
{

}

webapp/Pages/Favorites.cshtml
@page
@model Blitzmove.Pages.FavoritesModel;
@{
    ViewData["Title"] = "Favorites";
    var myfavs = Model.MyFavorites.ToList();
}

<div class="container">
    <h2 class="title"> 
        Favorites
        <img class="mt-3 float-right" src="/pics/no_fav.png" />
    </h2>

    @if(myfavs.Count() == 0){
        <div class="container watermark">
            <span class="fs-20 chelseafont"> No Favorites. </span>
        </div>
    }
    else{
        <div class="container favorites">

            <form method="post" asp-antiforgery="true">

                <ul class="list-group-fav">

                    @foreach (var fav in myfavs)
                    {
                        @if (fav == null) {continue;}

                        <li>
                            <a asp-page="/Place" asp-route-id="@fav.Id" class="list-group-item list-group-item-action flex-column align-items-start">
                            <div class="row">                                
                                <div class="col-4">
                                    <div class="row">                                
                                        <div class="col-6 col-sm-3">
                                            <button style="height:40px" class="btn btn-link deletefav" type="submit" asp-page-handler="delete" asp-route-fav="@fav.Id"> 
                                                <i class="fa fa-times text-danger"></i> 
                                            </button> 
                                        </div>
                                        <div class="col-6 col-sm-9">
                                            @if(fav.Pictures.Count != 0)
                                            {
                                                <img class="imgpreview" src="@fav.GetInlinePictureSrc(0)" />
                                            }
                                            else { <img class="imgpreview" src="/pics/default-place.png" /> }
                                        </div>
                                    </div>
                                </div>

                                <div class="col-6 offset-2">
                                    <div class="d-flex w-100 justify-content-between">
                                        <div id="rentandbeds">
                                            <h5 class="fw-211"> $@fav.Rent </h5>
                                            @if(@fav.Bedrooms != 0)
                                            {
                                                <p class="fs-17"> @fav.Bedrooms BEDS </p>
                                            }
                                            else 
                                            {
                                                <p class="fs-17"> STUDIO </p>
                                            }
                                        </div>
                                        
                                    </div>
                                </div>                    
                            </div>
                            </a>
                        </li>
                    }

                </ul>

            </form>
        </div>
    }

</div>

webapp/Pages/MyBalance.cshtml
@page
@{
    ViewData["Title"] = "My Balance";
}

<div class="container">
    <h2 class="title">
        My Balance 
        <img class="mt-3 mb-5 float-right" src="/pics/wallet.png" />
    </h2>

    
</div>

@section Scripts
{

}

webapp/Pages/MyPlaces.cshtml
@page
@model Blitzmove.Pages.MyPlacesModel
@{
    ViewData["Title"] = "My Places";
    var myPlaces = Model.MyPlaces.ToList();
}

<div class="container">
    
    <h2 class="title"> 
        My Places
        <img class="mt-3 mb-5 float-right" src="/pics/img_places.png" />
    </h2>

    @if(myPlaces.Count() == 0){
        <div class="container watermark">
            <span class="fs-20 chelseafont"> You haven&#39;t added any place yet.</span>
        </div>
    }
    else{
        <form id="myplacesform" method="post" asp-antiforgery="true">
            <table class="table">
                <tbody>
                    @foreach (var p in myPlaces)
                    {
                        @** The Place **@
                        <tr class="beigerow">
                            <td class="text-center fs-18"> 
                                <span>
                                    <b>@p.place.VisitorCount</b> Views 
                                    <!-- <i style="color:rgb(255, 200, 98);" class="fa fa-question-circle" 
                                        data-toggle="tooltip" data-placement="top" title="Registered Users only"></i> -->
                                </span>
                            </td>
                            <td class="text-center fs-18">
                                <a asp-page="./Place" asp-route-id="@p.place.Id"> <b>@p.place.Address</b> </a>
                            </td>
                            <td class="text-center fs-18">
                                <b>@p.place.NumberOfApplicants</b> Applicants
                            </td>
                            <td class="text-center">
                                <a role="button" class="btn btn-sm btn-warning" asp-page="./CreatePlace" asp-route-id="@p.place.Id"> Edit </a>
                                <a role="button" class="btn btn-sm btn-danger btn-delete" href="#placeModal" data-toggle="modal">  Delete  </a>
                                <button class="d-none finalDelete" type="submit" asp-page-handler="delete" asp-route-id="@p.place.Id"> Delete </button>
                            </td>
                        </tr>

                        @** The Applicants **@
                        @foreach (var applicant in p.ListOfApplicants)
                        {
                        <tr>
                            <td style="display:table-cell;vertical-align:middle;" class="p-0 text-center fs-15">
                                @if(@applicant.ProfilePic != null)
                                {
                                    <img class="applicant-profile-pic" src=@applicant.ProfilePic>
                                }
                                else{
                                    <img class="applicant-profile-pic" src="/pics/profile_pic.png">
                                }
                            </td>
                            
                            <td style="display:table-cell; vertical-align:middle;" class="text-center fs-15">

                                <p class="mb-2 mt-2"> @applicant.Username is offering <b>$@applicant.PromisedReward</b>. </p>

                                @if (@applicant.JobTitle != null)
                                {
                                    <span class="d-inline-block"> <i>Job Title:</i>  <b>@applicant.JobTitle</b> </span>
                                }  
                                @if (@applicant.Salary !=0)
                                {
                                    <span class="d-inline-block">  <i>Yearly Salary:</i>  <b>$@applicant.Salary</b> </span>
                                }
                                @if (@applicant.CreditScore != 0)
                                {
                                    <span class="d-inline-block">  <i>Credit Score:</i> <b>@applicant.CreditScore</b> </span>
                                }
                                
                                @if (@applicant.Details != null)
                                {
                                    <p class="application-details"> @applicant.Details </p>
                                }                  
                                
                            </td>

                            <td style="display:table-cell;vertical-align:middle;" class="text-center fs-15">
                                @if(applicant.ApplicationStatus == -1){
                                    <span class="badge badge-primary">Waiting for action</span> 
                                }
                                else if(applicant.ApplicationStatus == 0 || applicant.ApplicationStatus == -2 ){
                                    <span class="badge badge-danger">Declined</span>
                                }
                                else if(applicant.ApplicationStatus == 1){
                                    <span class="badge badge-warning">Invited</span>
                                }
                                else if(applicant.ApplicationStatus == 2){
                                    <span class="badge badge-success">Payment requested</span> 
                                }
                            </td>

                            <td class="text-center" style="display:table-cell;vertical-align:middle;">

                                @if(applicant.ApplicationStatus != -2){
                                    <button id="actiondropdown" type="button" class="btn btn-sm btn-outline-info dropdown-toggle" 
                                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Action
                                    </button>
                                }
                                else{
                                    <button id="actiondropdown" type="button" class="btn btn-sm btn-outline-info dropdown-toggle" 
                                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" disabled>
                                        Action
                                    </button>
                                }
                            
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="actiondropdown">
                                    <button type="submit" class="dropdown-item fs-15" asp-page-handler="Invite" asp-route-id="@p.place.Id" asp-route-query="@applicant.ApplicationId"> Invite for a visit </button>
                                    <button type="submit" class="dropdown-item fs-15" asp-page-handler="Decline" asp-route-id="@p.place.Id" asp-route-query="@applicant.ApplicationId"> Decline Offer </button>
                                    @if(applicant.ApplicationStatus != 2){
                                        <button type="submit" class="dropdown-item fs-15" asp-page-handler="RequestPayment" asp-route-id="@p.place.Id" asp-route-query="@applicant.ApplicationId"> Request Payment </button>
                                    }
                                    else{
                                        <button type="submit" class="dropdown-item fs-15" asp-page-handler="CancelPaymentRequest" asp-route-id="@p.place.Id" asp-route-query="@applicant.ApplicationId"> Cancel Payment Request </button>
                                    }
                                    <a role=button class="dropdown-item fs-15" data-toggle="modal" href="#MessageModal" 
                                       data-applicantid="@applicant.Id" data-username="@applicant.Username"> Send Message </a>
                                </div>
                                
                            </td>
                        </tr>
                        }
                    }
                </tbody>
            </table>
        </form>
    }

    <div id="placeModal" class="modal hide" role="dialog" aria-labelledby="deletePlaceModal" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="fw-111 float-left" id="deletePlaceModal">Confirmation</h4>
                </div>
                <div class="modal-body">
                    <span class="fs-18"> This place will be permanently deleted. Are you sure ? </span>
                </div>
                <div class="modal-footer">
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
                    <button id="actionDelete" class="btn btn-danger">Delete</button>
                </div>
            </div>
        </div>
    </div>

    <div id="MessageModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="MessageModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div id="MessageModalContent" class="modal-content">

                <div class="modal-body">
                    <form method="post">
                        <h5 class="modal-title fs-20 pb-3" id="MessageModalLabel">New Message</h5>

                        <input type="hidden" class="form-control" asp-for="ApplicantId" id="modal-applicantid">

                        <textarea class="form-control" rows=3 asp-for="Message" id="modal-textmessage"></textarea>

                        <div class="text-center pt-3">
                            <button type="submit" class="btn btn-primary" asp-page-handler="Message"> Send </button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>

</div>

@section Scripts
{

}